site: dizzy f00d
title: dizzy f00d's blog
greetings: Blog
description: >-
  Motto: Be neither arrogant nor impetuous, be unyielding; be strict with yourself and be lenient towards others.
lang: en-GB
timezone:  Europe/London
repo: https://github.com/dizzyf00d/dizzyf00d.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"


author:
  name: dizzy f00d
  bio: blog
  username: dizzyf00d # general username
  github: dizzyf00d # github username
  twitter: dizzyf00d # twitter username
  email: dizzyf00d@outlook.com # email address


# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900


# URL settings
url: "https://dizzyf00d.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site is not in the root of the host.
permalink: pretty


# local
url: "http://localhost:4000"
baseurl: ""


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md


compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]


sass:
  sass_dir: _sass
  style: compressed


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links


collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


relative_links:
  enabled:     true
  collections: false
